// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7DaWzmh9NWMqOrqZpx42tyurANyw9ryM',
    appId: '1:780710305917:web:1cdd32c2ca868a646f9114',
    messagingSenderId: '780710305917',
    projectId: 'busapp-33bff',
    authDomain: 'busapp-33bff.firebaseapp.com',
    storageBucket: 'busapp-33bff.firebasestorage.app',
    measurementId: 'G-2VVL4DF6LM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDfVMTzzkWHuLPK5WtkpS2rWqaW2o6RUA',
    appId: '1:780710305917:android:6377a58b8ca1049f6f9114',
    messagingSenderId: '780710305917',
    projectId: 'busapp-33bff',
    storageBucket: 'busapp-33bff.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAu1fivM42GJG3T7D4NugZAtGmD7mRF5oA',
    appId: '1:780710305917:ios:3954306c1efa5f586f9114',
    messagingSenderId: '780710305917',
    projectId: 'busapp-33bff',
    storageBucket: 'busapp-33bff.firebasestorage.app',
    iosBundleId: 'com.example.busapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAu1fivM42GJG3T7D4NugZAtGmD7mRF5oA',
    appId: '1:780710305917:ios:3954306c1efa5f586f9114',
    messagingSenderId: '780710305917',
    projectId: 'busapp-33bff',
    storageBucket: 'busapp-33bff.firebasestorage.app',
    iosBundleId: 'com.example.busapp',
  );
}
