// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwkKyX6t55wwsMXOE5iqXF4wjONX_I3h0',
    appId: '1:428945016380:web:21c911e3fcb7217ce1a539',
    messagingSenderId: '428945016380',
    projectId: 'busroute-72f84',
    authDomain: 'busroute-72f84.firebaseapp.com',
    storageBucket: 'busroute-72f84.firebasestorage.app',
    measurementId: 'G-BC9BTYRFSH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASrHBDwMM97Gj0cqQ_-df1csQ0SU2RPRM',
    appId: '1:428945016380:android:bbb0a5fd74ceebb7e1a539',
    messagingSenderId: '428945016380',
    projectId: 'busroute-72f84',
    storageBucket: 'busroute-72f84.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8W6yAK9y3uurJO37D3cS5i7DAPaZuNXs',
    appId: '1:428945016380:ios:c0f8260b28b2a684e1a539',
    messagingSenderId: '428945016380',
    projectId: 'busroute-72f84',
    storageBucket: 'busroute-72f84.firebasestorage.app',
    iosBundleId: 'com.example.busapp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8W6yAK9y3uurJO37D3cS5i7DAPaZuNXs',
    appId: '1:428945016380:ios:c0f8260b28b2a684e1a539',
    messagingSenderId: '428945016380',
    projectId: 'busroute-72f84',
    storageBucket: 'busroute-72f84.firebasestorage.app',
    iosBundleId: 'com.example.busapp',
  );
}
